template = "https://github.com/giellalt/template-lang-und"
rev_id = 287
template_sha = "15a8cf1917db1d48c56f7254ed58b4e74a6fcd9c"

[replacements]
__GLOTTOLOG_ID__ = "maku1278"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-mpu"
__UND2C__ = "mpu"
__UNDEFINED__ = "Makuráp"
__UND__ = "mpu"
